import { IQuizQuestion } from "./QuizQuestion";
import { Dispatch, SetStateAction } from 'react';
import { ISkinCondition } from "./SkinCondition";
import { IErrorResponse } from "./ErrorResponse";
import { IDashboardValue } from "./DashboardValue";
import { IRowData } from "./RowData";
import { IMoisturiserSize } from "./MoistuiserSize";
import { IShopifyUIProduct } from "./ShopifyProduct";

interface IQuiz {
  isQuizVisible: boolean;
  toggleQuizVisibility: Dispatch<SetStateAction<boolean>>;
  cartData: IRowData[];
  updateCartData: Dispatch<SetStateAction<IRowData[]>>;
  progressCount: number;
  updateCount: Dispatch<SetStateAction<number>>;
  quizQuestions: IQuizQuestion[];
  updateQuizQuestions: Dispatch<SetStateAction<IQuizQuestion[]>>;
  ingredients: IShopifyUIProduct[];
  updateIngredients: Dispatch<SetStateAction<IShopifyUIProduct[]>>;
  questionsAnswered: IQuizQuestion[];
  updateQuestionsAnswered: Dispatch<SetStateAction<IQuizQuestion[]>>;
  questionInputAnswer: string;
  updateQuestionInputAnswer: Dispatch<SetStateAction<string>>;
  selectedSkinConditions: ISkinCondition[];
  updateSelectedSkinConditions: Dispatch<SetStateAction<ISkinCondition[]>>;
  userName: string;
  updateUserName: Dispatch<SetStateAction<string>>;
  baseIngredient: IShopifyUIProduct;
  updateBaseIngredient: Dispatch<SetStateAction<IShopifyUIProduct>>;
  setQuizToCompleted: Dispatch<SetStateAction<boolean>>;
  isQuizCompleted: boolean;
  isAnswersPanelVisible: boolean;
  setAnswersPanelVisibility: Dispatch<SetStateAction<boolean>>;
  hasApplicationErrored: IErrorResponse;
  setApplicationError: Dispatch<SetStateAction<IErrorResponse>>;
  dashboardValues: IDashboardValue;
  saveDashboardValues: Dispatch<SetStateAction<IDashboardValue>>;
  analyticsId: string;
  saveAnalyticsId: Dispatch<SetStateAction<string>>;
  areSummaryCTAsVisible: boolean;
  showSummaryCTAs: Dispatch<SetStateAction<boolean>>;
  serums: IShopifyUIProduct[];
  updateSerums: Dispatch<SetStateAction<IShopifyUIProduct[]>>;
  isLoading: boolean;
  toggleLoading: Dispatch<SetStateAction<boolean>>;
  isAmendSelected: boolean;
  toggleAmendSelected: Dispatch<SetStateAction<boolean>>;
  moisturiserSizes: IMoisturiserSize[];
  toggleSelectedMoisturiserSizes: Dispatch<SetStateAction<IMoisturiserSize[]>>;
  longUniqueId: number;
  saveLongUniqueId: Dispatch<SetStateAction<number>>;
}

export default IQuiz;